// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import "gs-reader-lite/server/model/internal"

// RssFeedChannel is the golang structure for table rss_feed_channel.
type RssFeedChannel internal.RssFeedChannel

// Fill with you ideas below.
