// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import "gs-reader-lite/server/model/internal"

// RssFeedItem is the golang structure for table rss_feed_item.
type RssFeedItem internal.RssFeedItem

// RFIWithoutContentFieldSql SQL select filed without channel description.
var (
	RFIWithoutContentFieldSql = "rfi.id, rfi.channel_id, rfi.title, rfi.description, rfi.link, rfi.date, rfi.author, rfi.input_date, rfi.thumbnail"
)
