// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import "gs-reader-lite/server/model/internal"

// UserSubChannel is the golang structure for table user_sub_channel.
type UserSubChannel internal.UserSubChannel

// Fill with you ideas below.
