// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import "gs-reader-lite/server/model/internal"

// UserMarkFeedItem is the golang structure for table user_mark_feed_item.
type UserMarkFeedItem internal.UserMarkFeedItem

// Fill with you ideas below.
