// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserMarkFeedItem is the golang structure for table user_mark_feed_item.
type UserMarkFeedItem struct {
	UserId        string      `orm:"user_id"         json:"userId"`        //
	ChannelItemId string      `orm:"channel_item_id" json:"channelItemId"` //
	InputTime     *gtime.Time `orm:"input_time"      json:"inputTime"`     //
	Status        int         `orm:"status"          json:"status"`        //
}
