// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserSubChannel is the golang structure for table user_sub_channel.
type UserSubChannel struct {
	UserId    string      `orm:"user_id"    json:"userId"`    //
	ChannelId string      `orm:"channel_id" json:"channelId"` //
	InputTime *gtime.Time `orm:"input_time" json:"inputTime"` //
	Status    int         `orm:"status"     json:"status"`    //
}
